name: 🐞 Bug Report
description: Report a bug if something isn't working as expected.
body:
  - type: textarea
    id: version
    attributes:
      label: Directorist version
      placeholder: eg. v7.2, v7.2+ etc
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: eg. PHP version, Current theme etc
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: A clear and concise description of what the bug is, and what is the expected behavior
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Attach screenshot(s) or recording(s) directly by dragging & dropping.
      placeholder: |
        1. Go to ..
        2. Click on ..
        3. Scroll down to ..
        4. See error ..
    validations:
      required: true
  - type: checkboxes
    id: isolating
    attributes:
      label: Isolating the problem
      options:
        - label: I have reproduced this bug in localhost.
        - label: This bug happens with a default WordPress theme active (eg. 2021, 2022 etc).
