blank_issues_enabled: true
contact_links:
  - name: ❓ Support
    url: https://wpwax.com/contact/
    about: For any support or feature request, please head over to our official support channel.
  - name: Documentation
    url: https://wpwax.com/docs/logo-showcase-ultimate/
    about: To know more about logo showcase, please check out our official documentation.
